### ISSUE TITLE
.ods/.xls locked

### ISSUE THREAD

**Issue by virtualhealthcitizen** [talhusain/SoftwareEngineering#1]
![nope](https://cloud.githubusercontent.com/assets/11172321/18140063/866dc520-6f79-11e6-8610-5dc7f0070199.png)
I don't have Excel on my laptop or PC so can I just submit my availability in .xls or .ods (this would require adding either extension to the list of allowable extensions, I think. It seems I can't track the file at this time, which I need to do in order to commit)?? This isn't really an issue but my phone is dead at the moment, lol.

EDIT: At any rate, here you go:
![availability](https://cloud.githubusercontent.com/assets/11172321/18142889/249e6712-6f85-11e6-864a-f87f1b65be36.png)

**Comment by badstreff** [comment]
The university provides Office for [free](https://www.shsu.edu/dept/it@sam/technology-tutorials/home-use.html) if you want to download Office 2016. Also, I'm fine with you changing the format to .xls as I think excel can handle that just fine

**Comment by virtualhealthcitizen** [comment]
![nope](https://cloud.githubusercontent.com/assets/11172321/18142703/68a8cf52-6f84-11e6-903a-eb924bfbc63e.png)

Whelp.

EDIT: Thank you for the link to free Office btw!
