### ISSUE TITLE
plugin.py

### ISSUE THREAD

**Issue by virtualhealthcitizen** [talhusain/SoftwareEngineering#10]
Developers who wish to contribute to `plugin.py` should assign themselves (or be assigned) to this issue.

**Comment by badstreff** [comment]
I really like the idea of the [registry](https://github.com/faif/python-patterns/blob/master/registry.py) pattern for this.

Plugin implementers can setup their `__init__.py` to instantiate a plugin.
In whatever we decide the loader class to be, a try:except import statement can be made.
And we are done?

Seems reasonable to me.

**Comment by badstreff** [comment]
Partially implemented so far.

**Comment by badstreff** [comment]
We are no longer using the registry pattern.

The module needs to utilize get_all_plugins.py in db.py to parse each plugin. It is currently only parsing a static plugin

**Comment by badstreff** [comment]
2 things left to do before closing.
Pass the last_run date of the table to the plugin.
Update the last_run column, a function in db.py will need created for this.
