### ISSUE TITLE
Modify Dockerfile to Run nginx and uwsgi

### ISSUE THREAD

**Issue by badstreff** [talhusain/SoftwareEngineering#19]
Currently the Dockerfile users flasks built in webserver to serve content. The Dockerfile should be modified to use nginx and uwsgi, this will allow serving static content which flask is not very good at.

**Comment by badstreff** [comment]
Working on this :/

**Comment by virtualhealthcitizen** [comment]
I'll help out with this one.

**Comment by badstreff** [comment]
Done
