### ISSUE TITLE
Add provider column to the torrent table (db.py)

### ISSUE THREAD

**Issue by badstreff** [talhusain/SoftwareEngineering#50]
The provider should be a foreign key that references the URL in the plugins table.

**Comment by badstreff** [comment]
@talhusain, Below is the error I get when trying to run your changes

```
ajf023@AB1-4-66 /Volumes/Storage/SoftwareEngineering/debug (dev-plugin *)$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    main()
  File "main.py", line 14, in main
    db = Database('settings.conf')
  File "/Volumes/Storage/SoftwareEngineering/debug/db.py", line 41, in __init__
    self._initialize_tables()
  File "/Volumes/Storage/SoftwareEngineering/debug/db.py", line 49, in _initialize_tables
    cursor.execute("CREATE TABLE IF NOT EXISTS torrents "
psycopg2.ProgrammingError: syntax error at or near "provider"
LINE 1: ...tion_time TIMESTAMP,piece_length INT,pieces BYTEA)provider T...
                                                             ^
```

Please resolve it as soon as you can. To setup your branch correctly:
`git checkout dev`
`git branch dev-torrentprovidercolumn`
make your changes and test them with `python3 main.py`
Commit & Push your changes
Submit a PR

**Comment by badstreff** [comment]
I made a few changes on my end to get everything working, there's actually quite a bit that needed changed for adding this column. The DB tables are created manually, so once you have everything setup it should work correctly.

**Comment by badstreff** [comment]
1. The url column of plugins will need to be set as the primary key
2. A fake plugin will need loaded, I set the url to 'None'
3. The import_fake_torrents will need a column added using the 'None' plugin we added in step 2.
4. add_sample_torrents will need to use the 'None' plugin set in step 2

**Comment by badstreff** [comment]
The changes I described are implemented in PR #56
Let me know if there is anything you would change, I used your original code and fixed up the remaining statements.

**Comment by talhusain** [comment]
Aaaahhhh, you're right lol. Derp. Looks good to me

**Comment by badstreff** [comment]
I accepted it :P
