### ISSUE TITLE
Downloading a torrent using Python

### ISSUE THREAD

**Issue by virtualhealthcitizen** [talhusain/SoftwareEngineering#7]
We need to figure out how to download torrents with Python! :snake: 

Preferably without [subprocess](https://docs.python.org/2/library/subprocess.html).check_call( ) or any other open functions.

Look into the [libtorrent](http://www.libtorrent.org/) library.

**Comment by talhusain** [comment]
I'll look into this if no one else has done so already

**Comment by badstreff** [comment]
We are writing our own torrent downloading library, @squidmin  is working on it but I'm sure he would appreciate help

**Comment by badstreff** [comment]
Closing this as we are currently working on TorrentClient package.
